import Foundation

enum LoreCatalog {
    static let entries: [LoreEntry] = [
        LoreEntry(id: "desk", title: "THE RETURN CONTRACT", subtitle: "Security desk · carbon copy / MV-06", text: "MARA VALE — overnight recovery contractor. Your access begins at midnight. The morning van arrives at six.\n\nHandwritten beneath the signature: ‘They say my mother walked out. I remember her voice telling us to stay. There are two copies. I need the one they did not play.’\n\nA pencilled reminder circles a time: 03:17. Beneath it: ‘Voss left the witness in RESONANCE.’\n\nThe back of the page reads: ‘If you must shut both doors, count what it costs. The west machine needs a witness. The east one follows a voice. Whatever is inside the air handler needs moving air.’"),
        LoreEntry(id: "gallery", title: "A ROOM REMOVED", subtitle: "Exhibit gallery · visitor guide / revised 1994", text: "MORROW LISTENING INSTITUTE\n‘A voice is a room you can visit again.’\n\n01 / Welcome. 02 / Learn. 03 / Make. [Heavy black ink.] 05 / Remember.\n\nUnder a peeling strip of tape: ‘04 / RETURN — private listening appointments.’ Someone has crossed out ‘private’ and written ‘ONE WAY’.\n\nA child's drawing shows a woman speaking into a brass horn. On the other side of the wall, an identical woman has no mouth. The drawing is signed M. VALE, age 7.\n\nIn the margin, two boxed digits survived the revision: 0 4."),
        LoreEntry(id: "maintenance", title: "CONTINUITY SERVICE NOTE", subtitle: "Fabrication bench · A. Voss / 16 April 1994", text: "The Surveyor holds position while a live observer confirms its work. A dead feed is not an observer. Use the west barrier if it reaches the passage.\n\nThe Chorus follows the relay voice along adjacent corridors. Do not expect a distant loudspeaker to call it across the building. Do not run the air handler for comfort: it carries sound to the east passage.\n\nThe seam-cleaning frame is responding to retained heat. Purge the duct in short bursts before pressure reaches eighty. The motor locks out after a long burst; give it time to cool. Door seals do not cover a duct.\n\nP.S. Return channel access: use its room number, then the withheld-call total. Four figures, no separator. Someone has changed the label on the controller to make the channel look disconnected."),
        LoreEntry(id: "incident", title: "WITHHELD CALLS", subtitle: "Resonance archive · switchboard audit / 17 April 1994", text: "03:17 / external line available.\n03:17 / operator requesting immediate evacuation.\n03:17 / continuity supervisor redirects announcement to specimen storage.\n\nCalls withheld: 17. Public announcements delivered: 0.\n\nA later report describes ‘panic caused by convincing recorded voices’. Beneath it Ada Voss has written: ‘The panic was real. The voices telling them to remain seated were recordings.’\n\nA routing receipt gives one surviving destination: RETURN. Two stamped digits appear in the withheld column: 1 7.\n\n‘Do not cut the relay when the witness speaks. Give it a destination.’"),
        LoreEntry(id: "return", title: "THE UNPLAYED SIDE", subtitle: "Return chamber · routing instructions / retained original", text: "RETURN CHANNEL 04 / outbound witness line.\n\nThe archive begins its erase cycle at 04:00. The camera relay can hold a clean route open until morning. Select this room and transmit the voice after four. Have ten units available when you transmit. Keep the circuit powered until the morning exchange.\n\nRecording label: HELEN VALE — evacuation operator.\n\n‘Mara, if that is you: the voice in the gallery is mine, but I did not say it that night. That is what they kept. I sent the other side here.’\n\nThe red lamp beside OUTBOUND has never burned out. It has been waiting for an address."),
        LoreEntry(id: "testimony", title: "03:17 / WITNESS COPY", subtitle: "Resonance archive · time-aligned damaged recording", text: "[A door latches. Two low tones. A woman's breath.]\n\nHELEN VALE: ‘Seventeen calls, Elias. Children are asleep in the lower hall. Tell them to leave.’\n\nELIAS MORROW: ‘The collection must remain continuous.’\n\nADA VOSS: ‘Then I am making another copy.’\n\n[The loudspeaker plays Helen's voice: Please remain where you are. She speaks over herself.]\n\nHELEN: ‘That is not me. Mara, take the west stairs. Do not wait for my voice.’\n\nThe timestamp remains 03:17 while the waveform continues. The final breath is labelled as background noise."),
        LoreEntry(id: "blackout", title: "RESIDUAL INSTRUCTION", subtitle: "Security monitor · low-voltage afterimage", text: "The green phosphor fades slower than the room. A maintenance page becomes visible beneath the picture.\n\n‘SURVEY / preserve positions until witnessed.\nCHORAL / retain occupied voices.\nSEAM / seal heat in the collection.’\n\n‘They did not learn how to hate us. We never taught them how to stop.’ — A.V.\n\nAt the bottom: ‘M. VALE: transferred to exterior stairwell. H. VALE: status overwritten by continuity register.’\n\nFor a moment the empty fourth space on the map reads: SEND, NOT STORE."),
        LoreEntry(id: "ending", title: "MORNING RECEIPT", subtitle: "Institute security desk · printed at 06:00", text: "SHIFT COMPLETE. OPERATOR PRESENT.\n\nThe automatic van is empty except for an old case marked VALE. Inside is a duplicate visitor pass with your childhood photograph. Your contractor pass carries the same number.\n\nThe institute did not call a replacement guard. It recognised a returning participant.\n\nOn the back of the morning receipt, in a different ribbon: ‘An archive can preserve a voice. It cannot decide what that voice meant.’\n\nYou remember the missing place on the map. If the witness has a route out, the morning may carry more than a receipt.")
    ]

    static func entry(_ id: String) -> LoreEntry? { entries.first { $0.id == id } }
}
